name: release (linux)

on:
  release:
    types: [published]

env:
  binary_deep_name: target/release/shrapnel
  zip_name: shrapnel-${{ github.event.release.tag_name }}-x86_64-unknown-linux-gnu.7z

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install upx
        run: sudo apt-get install upx
      - name: Build
        run: cargo build --release --verbose
      - name: Strip
        run: strip ${{ env.binary_deep_name }}
      - name: Pack
        run: upx --best ${{ env.binary_deep_name }}
      - name: Zip
        run: 7z a ${{ env.zip_name }} ./${{ env.binary_deep_name }}
      - name: Publish to github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sh ./.github/scripts/upload-script.sh ${{ env.zip_name }}
