name: release (linux)

on:
  release:
    types: [published]

env:
  rustc_target_name: x86_64-unknown-linux-gnu
  binary_path: target/release
  binary_name: shrapnel
  zip_name: shrapnel-${{ github.event.release.tag_name }}-x86_64-unknown-linux-gnu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install upx
        run: sudo apt-get install upx
      - name: Build
        run: cargo build --release --verbose
      - name: Strip
        run: strip -p --strip-unneeded --remove-section=.comment ${{ env.binary_path }}/${{ env.binary_name }}
      - name: Pack
        run: upx --best target/release/shrapnel
      - name: Zip
        run: zip --junk-paths ${{ env.zip_name }} ${{ env.binary_path }}/${{ env.binary_name }}
      - name: DEBUG
        run: ls -alh
      - name: Publish to github release
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ env.zip_name }}.zip
