name: release (windows)

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install `cross`
        run: cargo install cross
      - name: Build
        run: cross build --release --verbose --target x86_64-pc-windows-gnu
      - name: Zip
        run: zip --junk-paths shrapnel-x86_64-pc-windows-gnu target/x86_64-pc-windows-gnu/release/shrapnel.exe
      - name: Publish to github release
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: shrapnel-x86_64-pc-windows-gnu.zip
