name: release (windows)

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --release --verbose
      - name: Publish to github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sh .\.github\scripts\upload-script.sh target/release/shrapnel.exe
